cli_decoding:
    adblock: false
    adblock_aggressive: false
    rpz: false
    wildcard: false
cli_testing:
    autocontinue: true
    ci:
        active: false
        branch: master
        command: ''
        commit_message: My Privacy DNS Firewall - AutoSave
        distribution_branch: master
        end_command: ''
        end_commit_message: My Privacy DNS Firewall - Results [GHA SKIP]
        max_exec_minutes: 15
    complements: false
    cooldown_time: 0.0
    days_between:
        db_clean: 28
        db_retest: 1
    db_type: csv
    display_mode:
        all: false
        colour: true
        dots: false
        execution_time: false
        less: true
        percentage: true
        quiet: false
        simple: false
        status: all
    file_filter: ''
    file_generation:
        analytic: true
        hosts: false
        no_file: false
        plain: true
        unified_results: false
    hosts_ip: 0.0.0.0
    inactive_db: true
    local_network: false
    max_workers: null
    mining: false
    preload_file: false
    sorting_mode:
        hierarchical: false
        standard: true
    testing_mode:
        availability: true
        reputation: false
        syntax: false
    whois_db: true
debug:
    active: false
    level: info
dns:
    protocol: UDP
    server:
        - 185.109.89.254
        - 130.225.244.166
        - 130.226.161.34
        - 185.38.24.52
        - 198.180.150.12
        - 94.126.178.9
        - 192.168.1.1
        - 91.239.100.100
        - 89.233.43.71
        - 95.216.209.53
        - 116.203.32.67
        - 185.121.177.177
        - 169.239.202.202
        - 161.97.219.84
        - 104.168.144.17
        - 163.172.168.171
        - 94.103.153.176
        - 207.192.71.13
        - 178.63.116.152
        - 138.68.128.160
        - 188.226.146.136
        - 45.55.97.204
        - 79.124.7.81
http_codes:
    list:
        potentially_down:
            - 400
            - 402
            - 404
            - 409
            - 410
            - 412
            - 414
            - 415
            - 416
            - 451
        potentially_up:
            - 300
            - 301
            - 302
            - 303
            - 304
            - 305
            - 307
            - 308
            - 403
            - 405
            - 406
            - 407
            - 408
            - 411
            - 413
            - 417
            - 418
            - 421
            - 422
            - 423
            - 424
            - 426
            - 428
            - 431
            - 500
            - 501
            - 502
            - 503
            - 504
            - 505
            - 506
            - 507
            - 508
            - 510
            - 511
        up:
            - 100
            - 101
            - 102
            - 200
            - 201
            - 202
            - 203
            - 204
            - 205
            - 206
            - 207
            - 208
            - 226
            - 429
    self_managed: false
links:
    api_date_format: https://pyfunceble.funilrys.com/api/date-format
    api_no_referer: https://pyfunceble.funilrys.com/api/no-referer
    api_no_referrer: https://pyfunceble.funilrys.com/api/no-referer
lookup:
    dns: true
    http_status_code: true
    netinfo: true
    reputation: false
    special: true
    timeout: 5
    whois: true
share_logs: false
user_agent:
    browser: firefox
    custom: null
    platform: linux
verify_ssl_certificate: false
