#!/usr/bin/env bash

set -e -xx
testFile="${TRAVIS_BUILD_DIR}/.pyfunceble/test.tmp"

touch "${testFile}"

git log --word-diff=porcelain -1 -p  -- submit_here/hosts.txt | grep -e "^+" | cut -d "+" -f2 | grep -vE "^(#|$)" >> "${testFile}"

#git log --word-diff=porcelain -1 -p  -- submit_here/mobile.txt | \
#  grep -e "^+" | cut -d "+" -f2 | grep -vE "^(#|$)" >> "${testFile}"

#git log --word-diff=porcelain -1 -p  -- submit_here/snuff.txt | \
#  grep -e "^+" | cut -d "+" -f2 | grep -vE "^(#|$)" >> "${testFile}"

cat "${testFile}"

SyntaxTest () {

    cd "${TRAVIS_BUILD_DIR}/.pyfunceble" || exit 1

    hash PyFunceble

	printf "\n\tYou are running with SyntaxTest\n\n"

	PyFunceble --version

    PyFunceble -m -nf --hierarchical -ex --syntax -f "${testFile}"
}

AvailabilityTest () {

    cd "${TRAVIS_BUILD_DIR}/.pyfunceble" || exit 1

    hash PyFunceble

	printf "\n\tYou are running with AvailabilityTest\n\n"

    PyFunceble -m -ex --share-logs --idna -a -nf \
            --hierarchical -f "${testFile}"
}

SyntaxTest

AvailabilityTest

rm -f "${testFile}"

exit ${?}


# Copyright: https://mypdns.org/
# Content: https://mypdns.org/spirillen/
# Source: https://mypdns.org/source/PornHosts/
# License: https://mypdns.org/my-privacy-dns/porn-records/-/blob/master/LICENSE
# License Comment: Creative Commons Attribution Share Alike 4.0 International
#
# License in short:
# You are free to copy and distribute this file for non-commercial uses,
# as long the original URL and attribution is included.
#
# Please forward any additions, corrections or comments by logging an
# issue at https://mypdns.org/my-privacy-dns/porn-records/-/issues

# Execute this script as bash porn/porn.sh from the root folder
