#!/usr/bin/env bash

set -e -xx
testFile="${TRAVIS_BUILD_DIR}/.pyfunceble/test.tmp"

touch "${testFile}"

git log --word-diff=porcelain -1 -p  -- submit_here/hosts.txt | grep -e "^+" | cut -d "+" -f2 | grep -vE "^(#|$)" >> "${testFile}"

#git log --word-diff=porcelain -1 -p  -- submit_here/mobile.txt | \
#  grep -e "^+" | cut -d "+" -f2 | grep -vE "^(#|$)" >> "${testFile}"

#git log --word-diff=porcelain -1 -p  -- submit_here/snuff.txt | \
#  grep -e "^+" | cut -d "+" -f2 | grep -vE "^(#|$)" >> "${testFile}"

cat "${testFile}"

SyntaxTest () {

    cd "${TRAVIS_BUILD_DIR}/.pyfunceble" || exit 1

    hash PyFunceble

	printf "\n\tYou are running with SyntaxTest\n\n"

	PyFunceble --version

    PyFunceble -m -nf --hierarchical -ex --syntax -f "${testFile}"
}

AvaileblityTest () {

    cd "${TRAVIS_BUILD_DIR}/.pyfunceble" || exit 1

    hash PyFunceble

	printf "\n\tYou are running with AvaileblityTest\n\n"

    PyFunceble -m -ex --share-logs --idna -a -nf \
            --hierarchical -f "${testFile}"
}

SyntaxTest

AvaileblityTest

rm -f "${testFile}"

exit ${?}


# Copyright: https://www.mypdns.org/
# Content: https://www.mypdns.org/p/Spirillen/
# Source: https://www.mypdns.org/source/PornHosts/
# License: https://www.mypdns.org/w/License
# License Comment: GNU AGPLv3, MODIFIED FOR NON COMMERCIAL USE
#
# License in short:
# You are free to copy and distribute this file for non-commercial uses,
# as long the original URL and attribution is included.
#
# Please forward any additions, corrections or comments by logging an
# issue at https://www.mypdns.org/maniphest/

# Execute this script as bash porn/porn.sh from the root folder
